### ISSUE TITLE
Document troubleshooting

### ISSUE THREAD

**Issue by acelaya** [shlinkio/shlink.io#142]
https://github.com/shlinkio/shlink/labels/troubleshooting

https://github.com/shlinkio/shlink-web-client/labels/troubleshooting

---

- [x] How do I change config options after installing Shlink (https://github.com/shlinkio/shlink/issues/929)
    * On latest version
    * On previous versions
- [x] BadMethodCallException: Undefined method `<methodName>` (https://github.com/shlinkio/shlink/issues/921)
    * If serving with a classic web server, restart the server/php-fpm process
- [x] What are the minimum grants required for the database user when using MySQL/Mariadb (https://github.com/shlinkio/shlink/issues/876)
    * It needs ALTER, CREATE, DROP, INDEX, LOCK TABLES, REFERENCES, SELECT, INSERT, DELETE and UPDATE.
- [x] How to install Shlink on a shared hosting (https://github.com/shlinkio/shlink/issues/839)
    * Shared hosting is not the target env
    * Try what's explained on ticket anyway
- [x] Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present.
    * If using a reverse proxy, make sure it forwards all headers generated by Shlink
- [x] I see "Mixed Content" errors in the browser's console
    * You cannot consume an http Shlink instance from a web client served with https
- [x] Short URLs work, but I can't consume Shlink from shlink-web-client
    * You cannot consume an http Shlink instance from a web client served with https
- [x] URLs on non-default domains result in 404 errors
    * If using a reverse proxy, make sure the `Host` header is properly forwarded to Shlink
- [x] I renamed Shlink's folder, and now nothing works
    * Clear cache file `data/cache/app_config.php`
- [x] When trying to update Shink I see "PHP Parse error: syntax error"
    * Make sure the installation is run with same PHP version
- [x] My visits location is always unknown
    * Make sure you set the GeoLite2 license key
- [x] Real time updates never get triggered
    * Make sure you set the Geolite2 license key
- [x] Shlink docker image does not listen to 443/https traffic
    * Yes, that's out of Shlink's scope. Use a reverse proxy in front of it that provides this capability
    * Examples (caddy, traefik, nginx, apache)
- [x] Troubleshoot errors when booting-up the docker image.
    * Set SHELL_VERBOSITY=3 env var
- [x] How to keep data on docker image between container recreations. (https://github.com/shlinkio/shlink/issues/861, https://github.com/shlinkio/shlink/issues/681)
    * Use external database for production
    * Explain why SQLite cannot use a volume (https://github.com/shlinkio/shlink-docker-image/issues/40#issuecomment-491924262)
